name: Dependabot Approve and Merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  dependabot:
    name: Dependabot
    uses: osinfra-io/pt-techne-misc-workflows/.github/workflows/dependabot.yml@cd7f9e2c86fe5bbafd21b8f12cc0e6cbe504f0f7  # v0.2.8
    secrets:
      pr_approve_and_merge_pem: ${{ secrets.PR_APPROVE_AND_MERGE_PEM }}
